# MPLAB IDE generated this makefile for use with GNU make.
# Project: USB_CDC_PICDEM.mcp
# Date: Fri Aug 24 15:45:01 2012

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

USB_CDC_PICDEM.cof : main.o usb_descriptors.o usb_device.o usb_function_cdc.o
	$(LD) /l"C:\MCC18\lib" "rm18f4550 - HID Bootload.lkr" "main.o" "usb_descriptors.o" "usb_device.o" "usb_function_cdc.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"USB_CDC_PICDEM.cof" /M"USB_CDC_PICDEM.map" /W

main.o : main.c ../../../MCC18/h/stdio.h ../../../MCC18/h/stdlib.h ../../../MCC18/h/string.h ../../microchip/include/usb/usb_common.h ../../microchip/include/usb/usb_device.h ../../microchip/include/USB/usb_function_cdc.h ../../../MCC18/h/adc.h ../../../MCC18/h/spi.h ../../../MCC18/h/delays.h main.c ../../microchip/include/USB/usb.h ../../microchip/include/GenericTypeDefs.h ../../../MCC18/h/stddef.h ../../microchip/include/Compiler.h ../../../MCC18/h/p18cxxx.h ../../../MCC18/h/p18f4550.h ../../../MCC18/h/stdarg.h usb_config.h ../../../MCC18/h/limits.h ../../microchip/include/usb/usb_ch9.h ../../microchip/include/usb/usb_hal.h ../../microchip/include/USB/usb_hal_pic18.h HardwareProfile.h HardwareProfile\ -\ PICDEM\ FSUSB.h ../../microchip/include/USB/usb_device.h ../../../MCC18/h/pconfig.h
	$(CC) -p=18F4550 /i"..\..\C:\USB_CDC_Device_project\CDC Basic Demo\CDC Basic Demo Firmware" -I"..\..\microchip\include" -I"C:\MCC18\h" "main.c" -fo="main.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_descriptors.o : usb_descriptors.c ../../../MCC18/h/stdio.h ../../../MCC18/h/stdlib.h ../../../MCC18/h/string.h ../../microchip/include/usb/usb_common.h ../../microchip/include/usb/usb_device.h ../../microchip/include/USB/usb_function_cdc.h usb_descriptors.c ../../microchip/include/USB/usb.h ../../microchip/include/GenericTypeDefs.h ../../../MCC18/h/stddef.h ../../microchip/include/Compiler.h ../../../MCC18/h/p18cxxx.h ../../../MCC18/h/p18f4550.h ../../../MCC18/h/stdarg.h usb_config.h ../../../MCC18/h/limits.h ../../microchip/include/usb/usb_ch9.h ../../microchip/include/usb/usb_hal.h ../../microchip/include/USB/usb_hal_pic18.h
	$(CC) -p=18F4550 /i"..\..\C:\USB_CDC_Device_project\CDC Basic Demo\CDC Basic Demo Firmware" -I"..\..\microchip\include" -I"C:\MCC18\h" "usb_descriptors.c" -fo="usb_descriptors.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_device.o : E:/karim/electronics/electronics\ books/My\ courses/embedded\ development/USB_CDC_Device_project/Microchip/USB/usb_device.c ../../../MCC18/h/stdio.h ../../../MCC18/h/stdlib.h ../../../MCC18/h/string.h ../../microchip/include/usb/usb_common.h ../../microchip/include/usb/usb_device.h E:/karim/electronics/electronics\ books/My\ courses/embedded\ development/USB_CDC_Device_project/Microchip/USB/usb_device.c ../../microchip/include/GenericTypeDefs.h ../../../MCC18/h/stddef.h ../../microchip/include/Compiler.h ../../../MCC18/h/p18cxxx.h ../../../MCC18/h/p18f4550.h ../../../MCC18/h/stdarg.h ../../microchip/include/USB/USB.h usb_config.h ../../../MCC18/h/limits.h ../../microchip/include/usb/usb_ch9.h ../../microchip/include/usb/usb_hal.h ../../microchip/include/USB/usb_hal_pic18.h HardwareProfile.h HardwareProfile\ -\ PICDEM\ FSUSB.h
	$(CC) -p=18F4550 /i"..\..\C:\USB_CDC_Device_project\CDC Basic Demo\CDC Basic Demo Firmware" -I"..\..\microchip\include" -I"C:\MCC18\h" "E:\karim\electronics\electronics books\My courses\embedded development\USB_CDC_Device_project\Microchip\USB\usb_device.c" -fo="usb_device.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_function_cdc.o : E:/karim/electronics/electronics\ books/My\ courses/embedded\ development/USB_CDC_Device_project/Microchip/USB/CDC\ Device\ Driver/usb_function_cdc.c ../../../MCC18/h/stdio.h ../../../MCC18/h/stdlib.h ../../../MCC18/h/string.h ../../microchip/include/usb/usb_common.h ../../microchip/include/usb/usb_device.h ../../microchip/include/USB/usb_function_cdc.h E:/karim/electronics/electronics\ books/My\ courses/embedded\ development/USB_CDC_Device_project/Microchip/USB/CDC\ Device\ Driver/usb_function_cdc.c ../../microchip/include/USB/usb.h ../../microchip/include/GenericTypeDefs.h ../../../MCC18/h/stddef.h ../../microchip/include/Compiler.h ../../../MCC18/h/p18cxxx.h ../../../MCC18/h/p18f4550.h ../../../MCC18/h/stdarg.h usb_config.h ../../../MCC18/h/limits.h ../../microchip/include/usb/usb_ch9.h ../../microchip/include/usb/usb_hal.h ../../microchip/include/USB/usb_hal_pic18.h
	$(CC) -p=18F4550 /i"..\..\C:\USB_CDC_Device_project\CDC Basic Demo\CDC Basic Demo Firmware" -I"..\..\microchip\include" -I"C:\MCC18\h" "E:\karim\electronics\electronics books\My courses\embedded development\USB_CDC_Device_project\Microchip\USB\CDC Device Driver\usb_function_cdc.c" -fo="usb_function_cdc.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "main.o" "usb_descriptors.o" "usb_device.o" "usb_function_cdc.o" "USB_CDC_PICDEM.cof" "USB_CDC_PICDEM.hex"

